<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceSubCategoryAppartmentPrice;

class ServiceSubCategoryAppartmentPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ServiceSubCategoryAppartmentPrice::truncate();
        $data = [
            ["sub_service_id" => 1, "appartment_type_id" => null, "base_price"=>50], 
            ["sub_service_id" => 2, "appartment_type_id" => 1, "base_price"=>100], 
            ["sub_service_id" => 2, "appartment_type_id" => 2, "base_price"=>110],
            ["sub_service_id" => 2, "appartment_type_id" => 3, "base_price"=>125],
            ["sub_service_id" => 2, "appartment_type_id" => 4, "base_price"=>150],
            ["sub_service_id" => 22, "appartment_type_id" => 1, "base_price"=>140],
            ["sub_service_id" => 22, "appartment_type_id" => 2, "base_price"=>145],
            ["sub_service_id" => 22, "appartment_type_id" => 3, "base_price"=>155],
            ["sub_service_id" => 22, "appartment_type_id" => 4, "base_price"=>165],
            ["sub_service_id" => 26, "appartment_type_id" => null, "base_price"=>85],
            ["sub_service_id" => 28, "appartment_type_id" => null, "base_price"=>60],
            ["sub_service_id" => 30, "appartment_type_id" => 1, "base_price"=>70],
            ["sub_service_id" => 30, "appartment_type_id" => 2, "base_price"=>90],
            ["sub_service_id" => 30, "appartment_type_id" => 3, "base_price"=>110],
            ["sub_service_id" => 30, "appartment_type_id" => 4, "base_price"=>130],
            ["sub_service_id" => 31, "appartment_type_id" => 1, "base_price"=>60],
            ["sub_service_id" => 31, "appartment_type_id" => 2, "base_price"=>80],
            ["sub_service_id" => 31, "appartment_type_id" => 3, "base_price"=>120],
            ["sub_service_id" => 31, "appartment_type_id" => 4, "base_price"=>160],
            ["sub_service_id" => 32, "appartment_type_id" => null, "base_price"=>30],
            ["sub_service_id" => 34, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 37, "appartment_type_id" => null, "base_price"=>20],
            ["sub_service_id" => 38, "appartment_type_id" => 1, "base_price"=>300],
            ["sub_service_id" => 38, "appartment_type_id" => 2, "base_price"=>350],
            ["sub_service_id" => 38, "appartment_type_id" => 3, "base_price"=>380],
            ["sub_service_id" => 38, "appartment_type_id" => 4, "base_price"=>420],
            ["sub_service_id" => 39, "appartment_type_id" => null, "base_price"=>45],
            ["sub_service_id" => 40, "appartment_type_id" => null, "base_price"=>350],
            ["sub_service_id" => 43, "appartment_type_id" => null, "base_price"=>200],
            ["sub_service_id" => 44, "appartment_type_id" => null, "base_price"=>0],
            ["sub_service_id" => 47, "appartment_type_id" => null, "base_price"=>40],
            ["sub_service_id" => 50, "appartment_type_id" => null, "base_price"=>45],
            ["sub_service_id" => 51, "appartment_type_id" => 1, "base_price"=>300],
            ["sub_service_id" => 51, "appartment_type_id" => 2, "base_price"=>350],
            ["sub_service_id" => 51, "appartment_type_id" => 3, "base_price"=>350],
            ["sub_service_id" => 51, "appartment_type_id" => 4, "base_price"=>375],
            ["sub_service_id" => 51, "appartment_type_id" => 5, "base_price"=>390],
            ["sub_service_id" => 52, "appartment_type_id" => null, "base_price"=>45],
            ["sub_service_id" => 53, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 55, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 56, "appartment_type_id" => null, "base_price"=>40],
            ["sub_service_id" => 59, "appartment_type_id" => null, "base_price"=>45],
            ["sub_service_id" => 60, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 61, "appartment_type_id" => null, "base_price"=>250],
            ["sub_service_id" => 62, "appartment_type_id" => null, "base_price"=>150],
            ["sub_service_id" => 63, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 64, "appartment_type_id" => null, "base_price"=>150],
            ["sub_service_id" => 65, "appartment_type_id" => null, "base_price"=>280],
            ["sub_service_id" => 66, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 67, "appartment_type_id" => null, "base_price"=>145],
            ["sub_service_id" => 68, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 69, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 70, "appartment_type_id" => null, "base_price"=>125],
            ["sub_service_id" => 71, "appartment_type_id" => null, "base_price"=>140],
            ["sub_service_id" => 72, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 73, "appartment_type_id" => null, "base_price"=>40],
            ["sub_service_id" => 76, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 77, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 78, "appartment_type_id" => null, "base_price"=>125],
            ["sub_service_id" => 79, "appartment_type_id" => null, "base_price"=>160],
            ["sub_service_id" => 80, "appartment_type_id" => null, "base_price"=>700],
            ["sub_service_id" => 85, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 86, "appartment_type_id" => null, "base_price"=>150],
            ["sub_service_id" => 89, "appartment_type_id" => null, "base_price"=>0],
            ["sub_service_id" => 90, "appartment_type_id" => null, "base_price"=>300],
            ["sub_service_id" => 91, "appartment_type_id" => null, "base_price"=>30],
            ["sub_service_id" => 92, "appartment_type_id" => null, "base_price"=>80],
            ["sub_service_id" => 95, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 96, "appartment_type_id" => null, "base_price"=>60],
            ["sub_service_id" => 97, "appartment_type_id" => null, "base_price"=>350],
            ["sub_service_id" => 98, "appartment_type_id" => null, "base_price"=>380],
            ["sub_service_id" => 99, "appartment_type_id" => null, "base_price"=>300],
            ["sub_service_id" => 100, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 101, "appartment_type_id" => null, "base_price"=>80],
            ["sub_service_id" => 102, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 103, "appartment_type_id" => null, "base_price"=>40],
            ["sub_service_id" => 104, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 105, "appartment_type_id" => null, "base_price"=>1050],
            ["sub_service_id" => 106, "appartment_type_id" => null, "base_price"=>700],
            ["sub_service_id" => 107, "appartment_type_id" => null, "base_price"=>180],
            ["sub_service_id" => 109, "appartment_type_id" => null, "base_price"=>180],
            ["sub_service_id" => 110, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 111, "appartment_type_id" => null, "base_price"=>50],
            ["sub_service_id" => 112, "appartment_type_id" => null, "base_price"=>200],
            ["sub_service_id" => 113, "appartment_type_id" => null, "base_price"=>400],
            ["sub_service_id" => 114, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 115, "appartment_type_id" => null, "base_price"=>90],
            ["sub_service_id" => 116, "appartment_type_id" => null, "base_price"=>100],
            ["sub_service_id" => 117, "appartment_type_id" => null, "base_price"=>80],
            ["sub_service_id" => 118, "appartment_type_id" => null, "base_price"=>330],
            ["sub_service_id" => 119, "appartment_type_id" => null, "base_price"=>600],
            ["sub_service_id" => 120, "appartment_type_id" => null, "base_price"=>400],
            ["sub_service_id" => 121, "appartment_type_id" => null, "base_price"=>40],
            ["sub_service_id" => 122, "appartment_type_id" => null, "base_price"=>80],
            ["sub_service_id" => 123, "appartment_type_id" => null, "base_price"=>220],
            ["sub_service_id" => 124, "appartment_type_id" => null, "base_price"=>440],
            ["sub_service_id" => 125, "appartment_type_id" => null, "base_price"=>660],
            ["sub_service_id" => 126, "appartment_type_id" => null, "base_price"=>250],
            ["sub_service_id" => 127, "appartment_type_id" => null, "base_price"=>150],
            ["sub_service_id" => 128, "appartment_type_id" => null, "base_price"=>180],
            ["sub_service_id" => 129, "appartment_type_id" => null, "base_price"=>250],
            ["sub_service_id" => 130, "appartment_type_id" => null, "base_price"=>150],
            ["sub_service_id" => 131, "appartment_type_id" => null, "base_price"=>180],
            ["sub_service_id" => 132, "appartment_type_id" => null, "base_price"=>350],
            ["sub_service_id" => 133, "appartment_type_id" => null, "base_price"=>85],
            ["sub_service_id" => 134, "appartment_type_id" => null, "base_price"=>0],


        ];
        ServiceSubCategoryAppartmentPrice::insert($data);
    }
}
