<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceSubCategory;

class ServiceSubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ServiceSubCategory::truncate();
        $data = [
            ["name" => "CA Carpet Cleaning", "parent_category_id" => 1, "is_independent" => 0, "is_show_to_client" => 1],
            ["name" => "CA Carpet seam", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Carpet Patch", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1],  
            ["name" => "CA Enzyme ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Install transition strip ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Pet odor ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Power wash Surface ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Re-stretch ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Red/juice stain ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Smoke odor ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Stair carpet loose ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Traffic areas ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA Urine/pet ", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CA water extraction", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "CA Carpet Replacement", "parent_category_id" => 1, "is_independent" => 0, "is_show_to_client" => 1],
            ["name" => "CO Concierge", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CO Janitorial", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "CO Porter", "parent_category_id" => 1, "is_independent" => 1, "is_show_to_client" => 1],
             
            ["name" => "FL Flooring", "parent_category_id" => 2, "is_independent" => 0, "is_show_to_client" => 1], 
            ["name" => "FL Apply polyurethane varnish", "parent_category_id" => 2, "is_independent" => 0, "is_show_to_client" => 1], 
            ["name" => "FL Sand and apply polyurethane varnish", "parent_category_id" => 2, "is_independent" => 0, "is_show_to_client" => 1], 
            ["name" => "FL Screen floor and apply polyurethane varnish", "parent_category_id" => 2, "is_independent" => 0, "is_show_to_client" => 1],

            ["name" => "JA Janitorial Cleaning", "parent_category_id" => 3, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "JA Additional cleaning", "parent_category_id" => 3, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "JA Complimentary service", "parent_category_id" => 3, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "JA Janitorial service response", "parent_category_id" => 3, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "JA Touch-up janitorial cleaning", "parent_category_id" => 3, "is_independent" => 1, "is_show_to_client" => 1],
            
            ["name" => "PT Paint", "parent_category_id" => 4, "is_independent" => 0, "is_show_to_client" => 1],
            ["name" => "PT Drywall", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Apply texture", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Drywall Service response", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "PT 2 tone semi-gloss baseboards, trims, frames and doors", "parent_category_id" => 4, "is_independent" => 0, "is_show_to_client" => 1],  
            ["name" => "PT Ceiling White", "parent_category_id" => 4, "is_independent" => 0, "is_show_to_client" => 1],
            ["name" => "PT Closet door", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Color change", "parent_category_id" => 4, "is_independent" => 0, "is_show_to_client" => 1], 
            ["name" => "PT Demolution", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Doors", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Express Paint", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Front door", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "PT Paint Additional Prep", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Paint cabinets- regular paint", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Paint-other", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Plaster", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Prime", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Remove wallpaper", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "PT Protect resident belongings", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Second coat", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Shelves Semigloss", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Touch-up paint", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PT Trash out", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "PT Protect residents belongings", "parent_category_id" => 4, "is_independent" => 1, "is_show_to_client" => 1], 

            ["name" => "PU Punch-Out", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "PU Access panel", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Appliance install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Baseboards", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Ceiling fan install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Closet Door Install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Cover base", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Door Lock", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Faucet Install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Garbage Disposal Install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install Counter top", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install Door Frame", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install Exhaust Fun", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install Medicine Cabinet", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install new window seal", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install plugs and switches 11-20", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install plugs and switches 21-30", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install plugs and switches 6-10", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install pre-hung door", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install Shelves in Closet", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install sink and faucet with or w/o vanity", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Install upper tank", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Light install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Punch-Out Additional", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Rangehood", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Re-grout tile", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Rebuild base under sink", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Remove laminate from cabinets", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Remove vanity cabinet and install new", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Replace Cabinets", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Shower Rods", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Sub floor", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Switches and outlets", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Tile Install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Toilet install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Vanity cabinet and sink install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Vinyl sheet Install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "PU Vinyl tiles Install", "parent_category_id" => 5, "is_independent" => 1, "is_show_to_client" => 1], 

            ["name" => "RF Refinish", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "Return Trip. No charge", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Backsplash", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Bondo repair", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Breakfast bar", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Ceramic tile repair", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Complimentary Service", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Deep Sanding", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Drain repair", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Extended walls", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Floor multistone", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Floor white", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Install drain", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Install drain and overflow set", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Install overflow", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Non-slip surface", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Re-grout", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Refinish cabinets inside and outside", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Refinish kitchen cabinets outside only", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Refinish Vanity Cabinet", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Refinish-other", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Remove liner", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Remove shower door", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Remove splash guard", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Shower stall", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Shower stall and surround", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Sink", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Soap Dish", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Stripping previous surface", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Surround wall accent multistone", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Surround walls", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Surround walls and extended walls", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Surround walls multistone", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Tile repair", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Travel Charge - Refinish", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Tub", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Tub and surround walls", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Tub and surround walls and extended walls", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Tub Fast-Dry Eco method", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Vanity cabinet", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Vanity multistone", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Vanity multistone double size", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Vanity white", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Vanity white double size", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1],
            ["name" => "RF Refinish countertop", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Service trip charge", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1], 
            ["name" => "RF Tile Installations/Ceramics", "parent_category_id" => 6, "is_independent" => 1, "is_show_to_client" => 1]           
        ];
        ServiceSubCategory::insert($data);
    }
}
